poolcare: emit error and exit right away
poolcare has long since been obsoleted by slindak and should not be used
by anyone. In order to make sure this doesn't happen, we emit error upon
poolcare startup. Future versions of slind-core will not ship poolcare at
all.

Signed-off-by: Alexander Shishkin <virtuoso@slind.org>

diff --git a/poolcare b/poolcare
--- a/poolcare
+++ b/poolcare
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+echo "ERROR: poolcare is prohibited by slind masters, use slindak instead."
+exit 1
+
 LIBUTILS=/usr/lib/slind-core/libutils.sh
 if [ -f "$LIBUTILS" ]; then
 	. $LIBUTILS
