eliminate slindjob-config dependency in injectdeb Signed-off-by: Alexander Shishkin <virtuoso@slind.org>

diff --git a/pool-injectdeb b/pool-injectdeb
--- a/pool-injectdeb
+++ b/pool-injectdeb
@@ -5,14 +5,19 @@ DEVSUITE="clydesdale"
 COMPONENTS="host-tools core gui security debug"
 ARCHES="arm powerpc i386 mips mipsel sh4 uclibc-arm uclibc-powerpc uclibc-i386 uclibc-mips uclibc-mipsel uclibc-sh4"
 
-SLINDJOB_CONFIG=~/.slindjob-config
-if [ -f $SLINDJOB_CONFIG ]; then
-	. $SLINDJOB_CONFIG
+SLIND_CONFIG=~/.slind-config
+if [ -f $SLIND_CONFIG ]; then
+	. $SLIND_CONFIG
 else
-	echo "Can't open $SLINDJOB_CONFIG"
+	echo "Can't open $SLIND_CONFIG"
 	exit 1
 fi
-REPODIR="$POOL_DIR"
+
+if [ -z "$REPODIR" ]; then
+	echo "REPODIR variable is not set in your $SLIND_CONFIG,"
+	echo "please specify it to be the path to your local repository"
+	exit 1
+fi
 
 LIBRARY=/usr/lib/slind-core/libpoolcare.sh
 if [ -f "$LIBRARY" ]; then
@@ -36,7 +41,7 @@ fi
 
 DEBPATH_LIST="`get_deb_poolpath $DEBNAME $SUITE`"
 for dir in $DEBPATH_LIST; do
-	dir="$POOL_DIR/$dir"
+	dir="$REPODIR/$dir"
 	echo "Copying to $dir"
 	mkdir -p "$dir"
 	cp "$DEBNAME" "$dir"
