Correctly pass proxy settings where it's needed
Signed-off-by: Wartan Hachaturow <wart@slind.org>

diff --git a/slind-host-tools-bootstrap b/slind-host-tools-bootstrap
--- a/slind-host-tools-bootstrap
+++ b/slind-host-tools-bootstrap
@@ -36,6 +36,10 @@ test -z "$TOOLCHAIN_BUILDDIR" && TOOLCHAIN_BUILDDIR="/tmp/tpkg"
 SRC_LIST=`conf_get_var_strict $SLIND_CONFIG slind-host-tools-bootstrap src_list`
 BIN_LIST=`conf_get_var_strict $SLIND_CONFIG slind-host-tools-bootstrap bin_list`
 
+[ -n "$HTTP_PROXY_URL" ] && PROXYENV="http_proxy=$HTTP_PROXY_URL"
+[ -n "$FTP_PROXY_URL" ]  && PROXYENV="$PROXYENV ftp_proxy=$FTP_PROXY_URL"
+CHROOTENV="env $PROXYENV $CHROOTENV"
+
 # hackaround for the case of non-existing locales
 export LC_ALL=C
 
@@ -58,7 +62,7 @@ build_package() {
 	local version="`override_get_pkg_version $pkgname $SLIND_SUITE`"
 
 	cd $BUILDDIR
-	fakeroot apt-get source --compile $pkgname=$version
+	fakeroot $CHROOTENV apt-get source --compile $pkgname=$version
 	if [ "$?" != "0" ]; then
 		die "Failed to build $pkgname package"
 	fi
@@ -72,14 +76,14 @@ fetch_grasp_git() {
 cd $BUILDDIR
 
 if [ -d grasp -a grasp/.git ]; then
-        cd grasp && git pull || die "Unable to pull from repo"
+        cd grasp && $CHROOTENV git pull || die "Unable to pull from repo"
         cd ..
 else
         # We assume here that master branch is what we want
         # This way we could handle both ssh:// and http:// repos.
         # If we are going to parse grasp files, then we have to use http-only
         # repo URL.
-        git clone ${GITBASE_URL}/grasp.git grasp
+        $CHROOTENV git clone ${GITBASE_URL}/grasp.git grasp
         [ -d grasp -a grasp/.git ] || die "Something wicked happened during git clone"
 fi
 }
@@ -115,7 +119,7 @@ get_overrides_db() {
 	fi
 
 	[ -f "$OVERRIDES_DB" ] || \
-		curl $SLIND_MIRROR/indices/overrides.db -o $OVERRIDES_DB || \
+		$CHROOTENV curl $SLIND_MIRROR/indices/overrides.db -o $OVERRIDES_DB || \
 			die "downloading of $SLIND_MIRROR/indices/overrides.db failed"
 }
 
@@ -164,7 +168,7 @@ build_base_host_tools_packages_init() {
 		grasp build $pkgname || die "Unable to 'grasp build' package $pkgname"
 	done
 	refresh_pool
-	$ROOT_CMD apt-get update || die "Could not update apt lists"
+	$ROOT_CMD $CHROOTENV apt-get update || die "Could not update apt lists"
 	build_base_host_tools_packages
 }
 
@@ -181,7 +185,7 @@ install_base_host_tools_packages() {
 	done
 	( cd $BUILDDIR && \
 	$ROOT_CMD dpkg -i $pkglist && \
-	$ROOT_CMD apt-get -f install --yes --force-yes )
+	$ROOT_CMD $CHROOTENV apt-get -f install --yes --force-yes )
 }
 
 # 4. build toolchain packages and store them to $POOLDIR
@@ -229,7 +233,7 @@ case "$1" in
 
 		case $1 in
 			--build)
-				$ROOT_CMD apt-get update
+				$ROOT_CMD $CHROOTENV apt-get update
 				get_overrides_db
 				build_base_host_tools_packages
 			;;
