New configuration style, no recursive calls.
Now that slind-core is safely expected to be inside chroot as a whole, there is
no need to copy stuff around or call ourselves recursively.

Signed-off-by: Wartan Hachaturow <wart@slind.org>

diff --git a/slind-host-tools-bootstrap b/slind-host-tools-bootstrap
--- a/slind-host-tools-bootstrap
+++ b/slind-host-tools-bootstrap
@@ -1,27 +1,35 @@
 #!/bin/bash
-set -e
+set -x
+
+LIBUTILS=/usr/lib/slind-core/libutils.sh
+if [ -f "$LIBUTILS" ]; then
+	. $LIBUTILS
+else
+	echo "Error: can't load library $LIBUTILS"
+	exit 1
+fi
+
+load_slind_config_common
+load_slind_config_maintainer_common
+load_suites_config
+
+LIBRARY=/usr/lib/slind-core/libpoolcare.sh
+if [ -f "$LIBRARY" ]; then
+	. $LIBRARY
+else
+	echo "Error: can't load library $LIBRARY"
+	exit 1
+fi
 
 SCRIPT_NAME=`basename $0`
 
-test -z "$REPODIR"            && REPODIR="/tmp/repo"
+# These two are internal to the tool, we don't care about them in global
+# configuration.
 test -z "$BUILDDIR"           && BUILDDIR="/tmp/base_pkg"
 test -z "$TOOLCHAIN_BUILDDIR" && TOOLCHAIN_BUILDDIR="/tmp/tpkg"
 
-HSTOOLS_SRC_PKGLIST="dpkg dpkg-cross slind-core toolchain-package grasp northern-cross fakechroot-cross cross-shell"
-HSTOOLS_TO_INSTALL="dpkg dpkg-dev dselect dpkg-cross grasp slind-core slind-maintainer-core toolchain-package-maintainer"
-
-POOLCARE_LIB="/usr/lib/slind-core/libpoolcare.sh"
-CONFIG_FILE=~/.slind-config
-if [ ! -f $CONFIG_FILE ]; then
-	if [ ! -f /etc/slind/slind-config ]; then
-		echo "Error: config file $CONFIG_FILE not found, please supply it."
-		exit 1;
-	fi
-	echo "Config file $CONFIG_FILE not found, create it from default config."
-	cp /etc/slind/slind-config $CONFIG_FILE
-fi
-
-[ -n "$DELIVERCMD" ] || DELIVERCMD=dummy_deliver_cmd
+SRC_LIST=`conf_get_var_strict $SLIND_CONFIG slind-host-tools-bootstrap src_list`
+BIN_LIST=`conf_get_var_strict $SLIND_CONFIG slind-host-tools-bootstrap bin_list`
 
 # hackaround for the case of non-existing locales
 export LC_ALL=C
@@ -42,7 +50,7 @@ cleanup() {
 build_package() {
 	local pkgname="$1"
 	
-	local version="`override_get_pkg_version $pkgname $SUITE`"
+	local version="`override_get_pkg_version $pkgname $SLIND_SUITE`"
 
 	cd $BUILDDIR
 	fakeroot apt-get source --compile $pkgname=$version
@@ -55,11 +63,19 @@ build_package() {
 # 1. get overrides.db
 get_overrides_db() {
 	echo "=== get overrides.db ==="
+	
+	# Check if it's a local mirror or not
+	if [ "${SLIND_MIRROR#http*:}" = "$SLIND_MIRROR" -a "${SLIND_MIRROR#ftp:}" = "$SLIND_MIRROR" ]; then
+	        # Since SLIND_MIRROR is used inside our working chroot, and we
+		# determined we're using a local directory, override
+		# SLIND_MIRROR with a path _inside_ chroot.
+	        SLIND_MIRROR="file:///SLIND"
+	fi
 
 	[ -f "$OVERRIDES_DB" ] || \
-		curl $SLIND_REPO/indices/overrides.db -o $OVERRIDES_DB
+		curl $SLIND_MIRROR/indices/overrides.db -o $OVERRIDES_DB
 	if [ "$?" != "0" ]; then
-		echo "Error: downloading of $SLIND_REPO/indices/overrides.db failed"
+		echo "Error: downloading of $SLIND_MIRROR/indices/overrides.db failed"
 		exit 1
 	fi
 	
@@ -69,16 +85,16 @@ dummy_deliver_cmd() {
 	local _pkg="$1"
 	local _suite="$2"
 
-	mv "$_pkg" "$POOLDIR"
+	mv "$_pkg" "$CHR_REPODIR"
 }
 
-# 2. build base host-tools packages and store them to $POOLDIR
+# 2. build base host-tools packages and store them to $CHR_REPODIR
 build_base_host_tools_packages() {
 	echo "=== building base host-tools packages ==="
 
 	local pkgname
 
-	for pkgname in $HSTOOLS_SRC_PKGLIST; do
+	for pkgname in $SRC_LIST; do
 		build_package $pkgname
 	done
 }
@@ -91,7 +107,7 @@ install_base_host_tools_packages() {
 	local pkglist
 
 	pkglist=""
-	for pkgname in $HSTOOLS_TO_INSTALL; do
+	for pkgname in $BIN_LIST; do
 		pkglist="$pkglist ${pkgname}_*.deb"
 	done
 	( cd $BUILDDIR && \
@@ -109,7 +125,7 @@ build_toolchain() {
 		rm -rf $TOOLCHAIN_BUILDDIR
 	fi
 
-	REPODIR=$REPODIR SRC_DIR=$TOOLCHAIN_BUILDDIR mktpkg $ARCH
+	BINARY_REPO=$CHR_REPODIR SRC_DIR=$TOOLCHAIN_BUILDDIR mktpkg $ARCH
 }
 
 # 5. deliver built packages to repository
@@ -119,34 +135,28 @@ deliver_packages() {
 	local p
 
 	for p in $from/*.deb; do
-		$DELIVERCMD $p $SUITE
+		$DELIVERCMD $p $SLIND_SUITE
 	done
 }
 
 case "$1" in
-	--chroot-build)
-		if [ ! -f ~/`basename $POOLCARE_LIB` ]; then
-			echo "Error: include file ~/`basename $POOLCARE_LIB` not found, please supply it."
-			exit 1
-		fi
-
-		. ~/`basename $CONFIG_FILE`
-		. ~/`basename $POOLCARE_LIB`
-
+	--build)
 		# Set up ^C handler
 		trap cleanup INT
 
 		cleanup "force"
+		
+		echo "=== start toolchain building ==="
 		mkdir -p $IDXDIR
 		mkdir -p $BUILDDIR
 		mkdir -p $POOLDIR
 
-		sudo apt-get update
+		$ROOT_CMD apt-get update
 
 		get_overrides_db
 		build_base_host_tools_packages
 		install_base_host_tools_packages
-		deliver_packages $BUILDDIR
+		deliver_packages $CHR_REPODIR
 
 		if [ -z "$2" ]; then
 			echo "Exiting, no arches were specified."
@@ -160,30 +170,6 @@ case "$1" in
 		
 		cleanup
 		echo "Done: check the chroot dir $POOLDIR for ready packages."
-		;;
-	--build)
-		if [ ! -f $POOLCARE_LIB ]; then
-			echo "Error: Include file $POOLCARE_LIB not found, please supply it."
-			exit 1;
-		fi
-
-		. $CONFIG_FILE
-		CHROOTCMD="$ROOTCMD chroot $TARGET su - build -c"
-
-		#prepare environment
-		cp $0             $TARGET/build/$SCRIPT_NAME
-		cp $CONFIG_FILE   $TARGET/build/`basename $CONFIG_FILE`
-		cp $POOLCARE_LIB  $TARGET/build/`basename $POOLCARE_LIB`
-		chmod a+x $TARGET/build/$SCRIPT_NAME
-
-		echo "=== start toolchain building ==="
-		shift
-		$CHROOTCMD "NO_CLEAN=$NO_CLEAN \
-			    REPODIR=$REPODIR \
-			    BUILDDIR=$BUILDDIR \
-			    TOOLCHAIN_BUILDDIR=$TOOLCHAIN_BUILDDIR \
-			/build/$SCRIPT_NAME --chroot-build $@"
-		exit $?
 		;;
 	*)
 		echo "Usage: $SCRIPT_NAME --build ARCHES"
